[package]
name = "Shamir"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"       # For modular arithmetic traits# For efficient modular operations
itertools = "0.14.0"
lazy_static = "1.5.0"
